project:
  type: website
jupyter: quarto.env

website:
  title: "Python programming I"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    toc: true         
    toc-depth: 3      
    toc-location: left 
    code-fold: false
    code-summary: "Reveal solution"
    theme: 
      light: united
      dark: superhero
    css: styles.css
