site_name: Python programming I
theme:
  name: material
nav:
  - Setup: index.md
  - Basics: 02-basics.md
  - NumPy: 03-numpy.md
  - Plotting: 04-plotting.md
  - DataFrames: 05-dataframes.md
  - Subsetting: 06-subsetting.md
  - Dicts: 07-dicts.md
  - IO: 08-io.md
  - Flow: 09-flow.md
  - Functions: 10-functions.md
  - Performance: 11-performance.md
  - Variable genes: 12-variable-genes.md
  - Clustering: 13-clustering.md
  - Linear models: 14-linear-models.md
  - K-means + project: 15-kmeans-project.md
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
